auth.py
#! /usr/bin/env python3

# Large amount of the code came from:
# https://github.com/udacity/ud330/blob/master/Lesson4/step2/project.py
from flask import Flask, render_template, request, redirect, url_for
from flask import make_response, flash, Blueprint
from flask import session as login_session

# import oauth
from oauth2client.client import flow_from_clientsecrets
from oauth2client.client import FlowExchangeError

import string
import random
import httplib2
import json
import requests
from controls import createUser

# import db
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from models import User, Base, Catagory, Item

# connect to db
engine = create_engine('sqlite:///catalog.db?check_same_thread=False')
Base.metadata.bind = engine
DBSession = sessionmaker(bind=engine)
session = DBSession()

auth = Blueprint('auth', __name__,
                 template_folder='templates')

client_number = "506926343220-t1f403simfav5cbr8i4udls4l3mr0d82"
CLIENT_ID = client_number + ".apps.googleusercontent.com"


# Create anti-forgery state token
@auth.route('/login')
def login():
    state = ''.join(random.choice(string.ascii_uppercase + string.digits)
                    for x in range(32))
    login_session['state'] = state
    return render_template('login.html', STATE=state)


@auth.route('/gconnect', methods=['GET', 'POST'])
def gconnect():
    # Validate state token
    if request.args.get('state') != login_session['state']:
        response = make_response(json.dumps('Invalid state parameter.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response
    # Obtain authorization code
    code = request.data

    try:
        # Upgrade the authorization code into a credentials object
        oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='')
        oauth_flow.redirect_uri = 'postmessage'
        credentials = oauth_flow.step2_exchange(code)
    except FlowExchangeError:
        response = make_response(
            json.dumps('Failed to upgrade the authorization code.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Check that the access token is valid.
    access_token = credentials.access_token
    url = ('https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=%s'
           % access_token)
    h = httplib2.Http()
    result = json.loads(h.request(url, 'GET')[1].decode('utf-8'))
    # If there was an error in the access token info, abort.
    if result.get('error') is not None:
        response = make_response(json.dumps(result.get('error')), 500)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Verify that the access token is used for the intended user.
    gplus_id = credentials.id_token['sub']
    if result['user_id'] != gplus_id:
        response = make_response(
            json.dumps("Token's user ID doesn't match given user ID."), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Verify that the access token is valid for this app.
    if result['issued_to'] != CLIENT_ID:
        response = make_response(
            json.dumps("Token's client ID does not match app's."), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    stored_access_token = login_session.get('access_token')
    stored_gplus_id = login_session.get('gplus_id')
    if stored_access_token is not None and gplus_id == stored_gplus_id:
        response_message = 'Current user is already connected.'
        response = make_response(json.dumps(response_message), 200)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Store the access token in the session for later use.
    login_session['access_token'] = credentials.access_token
    login_session['gplus_id'] = gplus_id

    # Get user info
    userinfo_url = "https://www.googleapis.com/oauth2/v1/userinfo"
    params = {'access_token': credentials.access_token, 'alt': 'json'}
    answer = requests.get(userinfo_url, params=params)

    data = answer.json()

    login_session['username'] = data['name']
    login_session['email'] = data['email']
    # ADD PROVIDER TO LOGIN SESSION
    login_session['provider'] = 'google'

    # see if user exists, if it doesn't make a new one
    user_id = session.query(User).filter_by(email=data["email"]).first().id
    if not user_id:
        user_id = createUser(login_session)
    login_session['user_id'] = user_id

    response = '<h1>Welcome, {}!</h1><img src="'.format(
        login_session['username'])
    flash("you are now logged in as %s" % login_session['username'])
    return response


# DISCONNECT - Revoke a current user's token and reset their login_session
@auth.route('/gdisconnect')
def gdisconnect():
    # Only disconnect a connected user.
    access_token = login_session.get('access_token')
    if access_token is None:
        response = make_response(
            json.dumps('Current user not connected.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response
    url = 'https://accounts.google.com/o/oauth2/revoke?token=%s' % access_token
    h = httplib2.Http()
    result = h.request(url, 'GET')[0]
    if result['status'] == '200':
        response = make_response(json.dumps('Successfully disconnected.'), 200)
        response.headers['Content-Type'] = 'application/json'
        return response
    else:
        response = make_response(json.dumps(
            'Failed to revoke token for given user.'), 400)
        response.headers['Content-Type'] = 'application/json'
        return response

templates/deleteitem.html
{% extends "template.html" %}

{% block title %}Delete Item{% endblock %}
{% block header %}Are you sure you want to delete {{item.name}}?{% endblock %}

{% block dbdata %}
    <form action="#" method = "post">
        <button type="submit" id="delete_submit">Confirm</button>
    </form>

    <br>

    <a href="{{url_for('viewAll_catagory', catagory=item.catagory)}}">Cancel</a>
{% endblock %}

templates/edititem.html
{% extends "template.html" %}

{% block title %}Edit Item{% endblock %}
{% block header %}Edit {{item.name}}:{% endblock %}

{% block dbdata %}
    <form action="#" method = "post">
        <label for="name"><h3>Name</h3></label>
        <input type ="text" maxlength="40" name="name" value="{{item.name}}">
        
        <label for="Catagory"><h3>catagory</h3></label>
        {% for catagory in catagories %}
                <input type="radio" name="catagory" value="{{catagory.name}}"
                    {% if catagory.name == item.catagory %}checked{% endif %}>{{catagory.name}}<br>
        {% endfor %}
        <br>

        <button type="submit" id="submit">Submit</button>
    </form>
{% endblock %}

templates/homepage.html
{% extends "template.html" %}
{% block title %}Homepage!{% endblock %}
{% block extras %}
  <button class=login>
    {% if log==False %}
      <a href='{{url_for("auth.login")}}'><strong>Login</strong></a>
    {% else %}
      <a href='{{url_for("auth.gdisconnect")}}'><strong>Logout</strong></a>
    {% endif %}
  </button>
{% endblock %}
{% block header %}Catalog{% endblock %}
{% block dbdata %}
  {% for catagory, items in items.items() %}
    <div class='data'>
      <h3>{{catagory.capitalize()}}</h3>
        <button class=new_item>
          <a href='{{url_for("newItem")}}'><strong>New Item</strong></a>
        </button><br>
        {% for item in items %}
          <span>{{item.name}}</span><br>
          <span>{{item.owner}}</span><br>
          <a href="{{url_for('editItem', item_name=item.name)}}">Edit</a><br>
          <a href="{{url_for('deleteItem', item_name=item.name)}}">Delete</a>
          <br><br>
        {% endfor %}  
    </div>  
  {% endfor %}
{% endblock %}

templates/login.html
<!-- Google+ API was shutdown on 3/7/2019. New OAuthFlow (listed below) uses the updated Google sign-in. -->
<!--You just need to update this in login.html page for Udacity's Full Stack nanodegree  -->
<!-- Below is the Google link I used for reference -->
<!-- https://developers.google.com/identity/sign-in/web/server-side-flow -->

<!Doctype html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://apis.google.com/js/client:platform.js?onload=start" async defer></script>
    <script src="static/auth.js">start();</script>
</head>


<body>
   
    <button id="signinButton">Google Signin</button>
    <div id="result"></div>
   
    <script>
      let STATE = "{{STATE}}";
      $('#signinButton').click(function() {
        auth2.grantOfflineAccess().then(signInCallback);
      });
    </script>
</body>

templates/newitem.html
{% extends "template.html" %}

{% block title %}New Item{% endblock %}
{% block header %}Make new item:{% endblock %}

{% block dbdata %}
    <form action="#" method = "post">
        <label for="name"><h3>Name</h3></label>
        <input type ="text" maxlength="40" name="name">
        
        <label for="Catagory"><h3>catagory</h3></label>
        {% for catagory in catagories %}
            <input type="radio" name="catagory" value="{{catagory.name}}" required>{{catagory.name}}<br>
        {% endfor %}
        <br>

        <button type="submit" id="submit">Submit</button>
    </form>
{% endblock %}

templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block viewport %}
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock %}
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Hello?{% endblock %}</title>
    {% block css %}
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='app.css') }}">
    {% endblock %}
    {% block js %}{% endblock %}
</head>

<body>
    {% block extras %}{% endblock %}
    <h1>{% block header %}{% endblock %}</h1>
    {% block dbdata %}{% endblock %}
</body>
</html>

templates/viewcatagory.html
{% extends "template.html" %}

{% block title %}View Catagory{% endblock %}

{% block header %}View items in {{catagory.capitalize()}}{% endblock %}

{% block dbdata %}
  <button class=new_item>
    <a href='{{url_for("newItem")}}'><strong>New Item</strong></a>
  </button>
  {% for item in items %}
    <br><br>
    <span class='item-name'>{{item.name}}</span><br>
    <span class='item-owner'>{{item.owner}}</span><br>
    <a href="{{url_for('editItem', item_name=item.name)}}">Edit</a><br>
    <a href="{{url_for('deleteItem', item_name=item.name)}}">Delete</a>
  {% endfor %}
{% endblock %}

templates/viewitem.html
{% extends "template.html" %}

{% block title %}View {{item.name}}{% endblock %}

{% block header %}{{item.name}}{% endblock %}

{% block dbdata %}
    <span class='item-owner'>{{item.owner}}</span><br>
    <span class='item-catagory'>{{item.catagory}}</span><br>
    <a href="{{url_for('editItem', item_name=item.name)}}">Edit</a><br>
    <a href="{{url_for('deleteItem', item_name=item.name)}}">Delete</a>
{% endblock %}

templates/viewowner.html
{% extends "template.html" %}

{% block title %}View Owner{% endblock %}

{% block header %}View items by {{owner}}{% endblock %}

{% block dbdata %}
  <button class=new_item>
    <a href='{{url_for("newItem")}}'><strong>New Item</strong></a>
  </button>
  {% for item in items %}
    <br><br>
    <span class='item-name'>{{item.name}}</span><br>
    <span class='item-catagory'>{{item.catagory}}</span><br>
    <a href="{{url_for('editItem', item_name=item.name)}}">
      Edit
    </a><br>
    <a href="{{url_for('deleteItem', item_name=item.name)}}">
      Delete
    </a>
  {% endfor %}
{% endblock %}